export const MEETING_CODE_PATTERN = /^[A-Z0-9]{6,16}$/;
export const PARTICIPANT_NAME_MAX_LENGTH = 64;
export const PARTICIPANT_NAME_MIN_LENGTH = 1;
export const REJOIN_TOKEN_COOKIE_NAME = "rejoin_token";
export const REJOIN_TOKEN_TTL_SECONDS = 300;
export const DEFAULT_MEETING_TTL_SECONDS = 7200;
export const SESSION_COOKIE_NAME = REJOIN_TOKEN_COOKIE_NAME;
