create table if not exists public.meetings (
  meeting_code text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  participant_id text primary key,
  meeting_code text not null references public.meetings(meeting_code) on delete cascade,
  display_name text not null,
  role text not null check (role in ('teacher', 'student')),
  status text not null check (status in ('pending', 'active', 'rejected')),
  join_identity_type text check (join_identity_type in ('email', 'phone')),
  join_identity_hash text,
  hand_raised boolean not null default false,
  hand_raised_at bigint,
  joined_at_ms bigint not null,
  last_seen_at_ms bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meeting_bans (
  meeting_code text not null references public.meetings(meeting_code) on delete cascade,
  identity_type text not null check (identity_type in ('email', 'phone')),
  identity_hash text not null,
  banned_by_participant_id text not null,
  banned_at timestamptz not null default now(),
  primary key (meeting_code, identity_hash)
);

create table if not exists public.host_controls (
  meeting_code text primary key references public.meetings(meeting_code) on delete cascade,
  mute_all_request_id integer not null default 0,
  force_student_cameras_on boolean not null default false,
  viva_time_enabled boolean not null default false,
  meeting_chat_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.room_events (
  id bigint generated by default as identity primary key,
  meeting_code text not null references public.meetings(meeting_code) on delete cascade,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_participants_meeting_status on public.participants(meeting_code, status);
create index if not exists idx_participants_meeting_identity_hash on public.participants(meeting_code, join_identity_hash);
create index if not exists idx_meeting_bans_meeting_identity_hash on public.meeting_bans(meeting_code, identity_hash);
create unique index if not exists idx_participants_participant_id on public.participants(participant_id);
create unique index if not exists idx_meetings_meeting_code on public.meetings(meeting_code);
create unique index if not exists idx_host_controls_meeting_code on public.host_controls(meeting_code);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_meetings_touch_updated_at on public.meetings;
create trigger trg_meetings_touch_updated_at
before update on public.meetings
for each row execute function public.touch_updated_at();

drop trigger if exists trg_participants_touch_updated_at on public.participants;
create trigger trg_participants_touch_updated_at
before update on public.participants
for each row execute function public.touch_updated_at();
